# Setup
title:               Hotpot
tagline:             'Hotspot'
description:         'A robotics blog'
url:                 https://phuicy.github.io/hotspot
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Guy Burroughes
  email:             gburroughes@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
